import math
print('하고 싶은 계산은?',end='')
d=input()
if(d=='등속 직선 운동'or d=='등속도 운동'or d=='등속도 직선 운동'):
    print('등속 직선 운동 계산기입니다')
    print('거리(m) = ', end='')
    a=input()
    print('속도(m/s) = ', end='')
    b=input()
    print('시간(s) = ', end='')
    c=input()
    if(a==''):
        result=float(b)*float(c)
        print('거리 = '+ str(result)+'m')
    elif(b==''):
        result=float(a)/float(c)
        print('속도 = '+ str(result)+'m/s')
    elif(c==''):
        result=float(a)/float(b)
        print('시간 = '+ str(result)+'s')
if(d=='가속도'):
    print('가속도 계산기입니다')
    print('주어진 값은?\n힘과 질량 : 1\n속도와 시간 : 2\n속도와 거리 : 3\n입력 후 Enter: ',end='')
    e=input()
    if(e=='1'):
        print('힘(N) = ',end='')
        f=input()
        print('질량(kg) = ',end='')
        g=input()
        result=(float(f)/float(g))
    if(e=='2'):
        print('시간(s) = ',end='')
        a=input()
        print('처음 속도(m/s) = ',end='')
        b=input()
        print('나중 속도(m/s) = ',end='')
        c=input()
        result=(float(c)-float(b))/float(a)
    if(e=='3'):
        print('처음 속도(m/s) = ',end='')
        a=input()
        print('나중 속도(m/s) = ',end='')
        b=input()
        print('거리(m) = ',end='')
        c=input()
        print('질량(kg) = ',end='')
        d=input()
        result=(((float(b))**2)-((float(a))**2))/(2*(float(c)))
        result2=(float(b)-float(a))/float(result)
        print('시간 = '+str(result2)+'s')
        result3=float(result)*float(d)
        print('알짜힘 = '+str(result3)+'N')
    print('가속도 = '+str(result)+'m/s²')
if(d=='등가속도 직선 운동'or d=='등가속도 운동'):
    print('등가속도 직선 운동 계산기 입니다')
    print('가속도(m/s²) = ',end='')
    f=input()
    print('처음 속도(m/s) = ',end='')
    o=input()
    print('나중 속도(m/s) = ',end='')
    p=input()
    print('시간(s) = ',end='')
    g=input()
    print('거리(m) = ',end='')
    h=input()
    if(h==''and o==''):
        result1=(((float(p)-(float(g)*float(f)))+float(p))/2)*float(g)
        result2=float(p)-(float(g)*float(f))
        print('처음 속도 = '+str(result2)+'m/s')
        print('이동 거리 = '+str(result1)+'m')